# Introducción a Numpy

Numpy es un módulo de Python desarollado principalmente para realizar operaciones con vectores y matrices.

Fue creado por Travis Oliphant en 2005 en formato open source.

## Documentación oficial 

En esta liga pueden encontrar toda la documentación oficial del módulo, hay varios tutoriales.
https://numpy.org/doc/stable/

Otras referencias:
    https://medium.com/@manmeet20singh11/introduction-to-python-jupyter-notebook-numpy-and-pandas-a57dc1086a8f
    https://discoverdatasciencelab.com/2018/10/09/introduccion-a-numpy-y-su-importancia-para-la-gestion-de-diferentes-tipos-de-datos/
    https://www.youtube.com/watch?v=xECXZ3tyONo

## Cargando Numpy

In [1]:
#cargando numpy sin abreviación
import numpy 

In [2]:
#cargando numpy con abreviación
import numpy as np

## Vectores 

Los vectores en Numpy son arreglos unidimensionales.

In [ ]:
#creando un vector
a = np.array([4,5,6])

In [ ]:
#imprimiendo el vector a en pantalla
print(a)

[4 5 6]


In [ ]:
#imprimiendo el vector como arreglo
a

array([4, 5, 6])

In [ ]:
#tipo de dato del vector
type(a)

numpy.ndarray

In [ ]:
#creando otro vector
b = np.array(['hola','mundo','adios'])
b

array(['hola', 'mundo', 'adios'], dtype='<U5')

In [ ]:
#tamaño del vector, observa que es un arreglo unidimensional de longitud 3
np.shape(b) 

(3,)

In [ ]:
#vector de ceros
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#vector de unos
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#vector de numeros aleatorios
np.random.seed(seed=100) #fijando la semilla=100
np.random.random(100)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333,
       0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749,
       0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375,
       0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045,
       0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497,
       0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606,
       0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ,
       0.74247969, 0.63018394, 0.58184219, 0.02043913, 0.21002658,
       0.54468488, 0.76911517, 0.25069523, 0.28589569, 0.85239509,
       0.97500649, 0.88485329, 0.35950784, 0.59885895, 0.35479561,
       0.34019022, 0.17808099, 0.23769421, 0.04486228, 0.50543143,
       0.37625245, 0.5928054 , 0.62994188, 0.14260031, 0.9338413 ,
       0.94637988, 0.60229666, 0.38776628, 0.363188  , 0.20434528,
       0.27676506, 0.24653588, 0.173608  , 0.96660969, 0.95701

In [ ]:
#vector con un valor repetido
c = np.full((100), 10)
c

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

## Matrices 

Las matrices en Numpy son arreglos multidimensionales.

In [ ]:
#se crea una matriz de 2x2
a = np.array( [[1,4],[6,8]] )
a

array([[1, 4],
       [6, 8]])

In [ ]:
#tamaño del arrego "a", observa que es un arreglo bidimensional
np.shape(a) 

(2, 2)

Observa la diferencia entre arreglos unidimensionales y multidimensionales

In [ ]:
#IMPORTANTE: Se crea un arreglo bidimensional de 1x3
w = np.array([[1,2,3]])
w

array([[1, 2, 3]])

In [ ]:
#IMPORTANTE: w es un arreglo bidimensional de dimensión 1x3
np.shape(w) 

(1, 3)

In [ ]:
#IMPORTANTE: se crea un arreglo unidimensional
z = np.array([1,2,3])
z

array([1, 2, 3])

In [ ]:
#IMPORTANTE: z es un arreglo unimensional de longitud 1x3
np.shape(z) 

(3,)

In [ ]:
#se crea un arreglo tridimensional (tensor)
p = np.array( [ [[1, 2],[3, 4]], [[5, 6],[7, 8]] ] )
p

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#p es un arreglo tridimensional de dimensión 2x2x2
np.shape(p) 

(2, 2, 2)

In [ ]:
#se crea un arreglo en 4 dimensiones
q = np.array( [[ [[1, 2],[3, 4]], [[5, 6],[7, 8]] ] , [ [[1, 2],[3, 4]], [[5, 6],[7, 8]] ]  ] )
q

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]])

In [ ]:
#q es un arreglo en 4 dimensiones
np.shape(q) 

(2, 2, 2, 2)

## Aritmética 

In [ ]:
#suma de los elementos de un vector
a = np.array([2,4,8])
np.sum(a) 

14

In [ ]:
#elemento minimo de un vector
np.min(a) 

2

In [ ]:
#elemento maximo de un vector
np.max(a)

8

In [ ]:
#suma de vectores entrada por entrada
a = np.array([1,2,3])
b = np.array([5,5,5])
c = a+b
print(c) 

[6 7 8]


In [ ]:
#resta de vectores entrada por entrada
a-b 

array([-4, -3, -2])

In [ ]:
#producto de vectores entrada por entrada
a*b 

array([ 5, 10, 15])

In [ ]:
#division de vectores entrada por entrada
a/b 

array([0.2, 0.4, 0.6])

In [ ]:
#vector elevado al cuadrado 2 entrada por entrada
a**2 #observa que es un doble asterisco

array([1, 4, 9])

In [ ]:
#vector elevado al cubo entrada por entrada
a**3

array([ 1,  8, 27])

In [ ]:
# suma de dos matrices entrada por entrada
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
a+b

array([[2, 4],
       [6, 8]])

In [ ]:
#resta de matrices entrada por entrada
a-b 

array([[0, 0],
       [0, 0]])

In [ ]:
#producto de matrices entrada por entrada
a*b 

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
#divisón de matrices entrada por entrada
a/b 

array([[1., 1.],
       [1., 1.]])

In [ ]:
#matriz "a" elevada al cuadrado entrada por entrada 
a**4

array([[  1,  16],
       [ 81, 256]])

In [ ]:
#producto matricial (algebra lineal)
a@b 

array([[ 7, 10],
       [15, 22]])

## Slicing

In [ ]:
# creando un arreglo de 3x3
a = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
#tomando todo el arreglo
a[:,:]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
#tomando la primera fila
a[0,:]

array([11, 12, 13])

In [ ]:
#tomando la primera columna
aux = a[:,0]

In [ ]:
aux

array([11, 14, 17])

In [ ]:
np.shape(aux)

(3,)

In [ ]:
#tomando las primeras dos filas
b = a[0:2,:]
b

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
#tomando las ultimas dos columnas
#OBSERVA QUE LLAMAMOS A LAS ULTIMAS 2 COLUMNAS CON 1:3
a[:,1:3]

array([[12, 13],
       [15, 16],
       [18, 19]])

In [ ]:
#tomando la segunda columna
a[:,1:2]

array([[12],
       [15],
       [18]])

In [ ]:
#tomando al primer elemento de la primera columna
a[0,0]

11

In [ ]:
#tomando al tercer elemento de la segunda fila
a[1,2]

16

In [ ]:
#tomando al maximo de cada columna
a.max(axis=0)

array([17, 18, 19])

In [ ]:
#sumando por columnas
a.sum(axis=0)

array([42, 45, 48])

In [ ]:
#tomando el maximo de cada fila
a.max(axis=1)

array([13, 16, 19])

## numpy.linalg

linalg es un submódulo de python con soporte para operaciones de álgebra lineal. 
    https://numpy.org/doc/stable/reference/routines.linalg.html

In [ ]:
#importa de módulo numpy el submódulo linalg 
from numpy import linalg as lga

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
#determinante de la matriz a
np.linalg.det(a) 

-2.0000000000000004

In [ ]:
#matriz inversa de la matriz a
lga.inv(a) 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#eigenvalores y eigenvectores de a
lga.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
w , z = lga.eig(a)

In [ ]:
#eigenvalores de la matriz a
w

array([-0.37228132,  5.37228132])

In [ ]:
#eigenvectores de la matriz a
z

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

## Ejercicios

1. Crea una matriz de 100x100 donde sus entradas sean números aleatorios.
2. Obtén la suma de las columnas de la matriz.
3. Obtén el promedio de valores de la matriz.
4. Obtén los últimos 10 valores de la última columna de la matriz.
5. Crea un arreglo tridimensional a partir de elementos de la matriz.
6. Crea un arreglo en 5 dimensiones a partir de los elementos de la matriz.
7. Eleva los elementos de la matriz al cubo.
8. Crea una segunda matriz y suma sus entradas entrada por entrada.
9. Obtén el producto matricial de ambas matrices.
10. Determina si la primera matriz es invertible, si lo es encuentra sus eigenvalores y eigenvectores, si no lo es intenta con otros números aleatorios hasta obtener una matriz invertible.

In [20]:
# Ejercicio 1
np.random.seed(seed=100)
x = np.random.random((100,100))
x

array([[5.43404942e-01, 2.78369385e-01, 4.24517591e-01, ...,
        6.41101259e-01, 2.00123607e-01, 6.57624806e-01],
       [7.78289215e-01, 7.79598399e-01, 6.10328153e-01, ...,
        9.02409503e-01, 1.62246919e-01, 4.05881322e-01],
       [4.17090736e-01, 6.95591028e-01, 4.24847238e-01, ...,
        4.37268841e-01, 4.21617509e-01, 5.47173771e-02],
       ...,
       [4.21180848e-01, 2.35263416e-01, 9.80352358e-01, ...,
        6.12607432e-01, 3.12077819e-01, 5.26514614e-01],
       [5.11328933e-01, 6.54087787e-01, 7.94117260e-01, ...,
        9.53289789e-01, 5.06908205e-01, 1.06125824e-02],
       [6.48360982e-01, 3.24140378e-04, 7.33029858e-01, ...,
        3.60737582e-01, 3.33155146e-02, 9.24292419e-02]])

In [25]:
# Ejercicio 2
y = np.array([[1, 2], [3, 4]])
display(y)
display(y.sum(axis=0))
y = np.matrix([[1, 2], [3, 4]])
display(y)
display(y.sum(axis=0))
x.sum(axis=0)
#Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. 
#Matrix objects are a subclass of ndarray, so they inherit all the attributes and methods of ndarrays.

array([[1, 2],
       [3, 4]])

array([4, 6])

matrix([[1, 2],
        [3, 4]])

matrix([[4, 6]])

array([43.29877569, 51.29865704, 46.62330682, 53.53271504, 55.04366652,
       52.1007976 , 46.61927057, 51.04068579, 45.44342257, 49.91722842,
       48.69817935, 53.96961077, 47.349908  , 51.8728318 , 52.3296154 ,
       50.04926725, 51.97746083, 49.95289998, 47.84285435, 48.23144807,
       49.62535349, 54.30697921, 47.54218001, 46.86754174, 47.60581702,
       51.26387464, 47.30888228, 52.68548363, 51.15065836, 53.18959375,
       44.85396107, 47.32310661, 51.16155129, 54.06240756, 44.8200404 ,
       49.79742677, 48.39657925, 51.17542874, 50.38300302, 49.18976099,
       45.23616342, 45.30892945, 54.58202755, 48.92973528, 50.37298902,
       46.77923579, 47.55934052, 53.05425247, 52.16627696, 50.37313487,
       48.4516388 , 47.86352924, 48.49765039, 51.4398538 , 49.20459684,
       52.68055833, 49.16777027, 54.19783969, 53.47917661, 53.55179845,
       48.57473775, 50.59047729, 48.77500826, 49.27388077, 45.73008752,
       48.74987071, 53.81148162, 47.84413347, 48.85308652, 49.75

In [26]:
# Ejercicio 3
x.mean(axis=None)
# los elementos de un array pueden cambiar su morfología a conveniencia

0.4976695227583672

In [35]:
# Ejercicio 4
display(y[-1:,-1])
x[-10:,-1]

matrix([[4]])

array([0.56495285, 0.32340562, 0.77316927, 0.74959471, 0.62001418,
       0.10886847, 0.65117297, 0.52651461, 0.01061258, 0.09242924])

In [52]:
# Ejercicio 5
x.reshape((10,10,100))

array([[[5.43404942e-01, 2.78369385e-01, 4.24517591e-01, ...,
         6.41101259e-01, 2.00123607e-01, 6.57624806e-01],
        [7.78289215e-01, 7.79598399e-01, 6.10328153e-01, ...,
         9.02409503e-01, 1.62246919e-01, 4.05881322e-01],
        [4.17090736e-01, 6.95591028e-01, 4.24847238e-01, ...,
         4.37268841e-01, 4.21617509e-01, 5.47173771e-02],
        ...,
        [8.86254141e-02, 9.83250377e-01, 4.79242982e-01, ...,
         7.67864594e-01, 8.86946972e-01, 8.29809368e-01],
        [9.58843079e-01, 9.11063996e-01, 1.19674784e-01, ...,
         5.21210306e-01, 8.89149454e-01, 7.24316153e-01],
        [6.52427303e-01, 5.73210877e-01, 1.85082757e-01, ...,
         1.50869224e-01, 3.69320635e-02, 5.97963743e-01]],

       [[2.77322775e-02, 3.82237264e-01, 9.53250912e-01, ...,
         6.42657437e-01, 9.95231024e-01, 5.42509891e-01],
        [7.32603504e-01, 3.66298120e-01, 7.44687448e-02, ...,
         5.05418291e-01, 4.65058802e-02, 3.41825062e-01],
        [4.31274613e-02, 

In [49]:
# Ejercicio 6
np.resize(x,(10,10,10,10,10))

array([[[[[5.43404942e-01, 2.78369385e-01, 4.24517591e-01, ...,
           8.25852755e-01, 1.36706590e-01, 5.75093329e-01],
          [8.91321954e-01, 2.09202122e-01, 1.85328220e-01, ...,
           1.71941013e-01, 8.16224749e-01, 2.74073747e-01],
          [4.31704184e-01, 9.40029820e-01, 8.17649379e-01, ...,
           2.52426353e-01, 7.95662508e-01, 1.52549712e-02],
          ...,
          [2.76765061e-01, 2.46535881e-01, 1.73608002e-01, ...,
           3.40385223e-01, 9.20556034e-02, 4.63498019e-01],
          [5.08698893e-01, 8.84601730e-02, 5.28035223e-01, ...,
           7.54348995e-01, 3.13066442e-01, 6.34036683e-01],
          [5.40404575e-01, 2.96793751e-01, 1.10787901e-01, ...,
           6.41101259e-01, 2.00123607e-01, 6.57624806e-01]],

         [[7.78289215e-01, 7.79598399e-01, 6.10328153e-01, ...,
           9.82407830e-01, 9.76500127e-01, 1.66694131e-01],
          [2.31781365e-02, 1.60744549e-01, 9.23496825e-01, ...,
           2.71830849e-01, 4.60601621e-01, 6.961615

In [53]:
# Ejercicio 7
x**3

array([[1.60461464e-01, 2.15707085e-02, 7.65045161e-02, ...,
        2.63499557e-01, 8.01484204e-03, 2.84403253e-01],
       [4.71436320e-01, 4.73819374e-01, 2.27347515e-01, ...,
        7.34870782e-01, 4.27099805e-03, 6.68647461e-02],
       [7.25590571e-02, 3.36559548e-01, 7.66828768e-02, ...,
        8.36075689e-02, 7.49472866e-02, 1.63823354e-04],
       ...,
       [7.47146636e-02, 1.30215654e-02, 9.42207580e-01, ...,
        2.29904135e-01, 3.03940594e-02, 1.45959138e-01],
       [1.33690671e-01, 2.79838923e-01, 5.00787992e-01, ...,
        8.66312984e-01, 1.30253068e-01, 1.19526232e-06],
       [2.72552778e-01, 3.40564520e-11, 3.93880966e-01, ...,
        4.69433597e-02, 3.69776729e-05, 7.89638241e-04]])

In [61]:
# Ejercicio 8
np.random.seed(seed=100)
y = np.random.random((100,100))
z = x+y
(z/2)

array([[5.43404942e-01, 2.78369385e-01, 4.24517591e-01, ...,
        6.41101259e-01, 2.00123607e-01, 6.57624806e-01],
       [7.78289215e-01, 7.79598399e-01, 6.10328153e-01, ...,
        9.02409503e-01, 1.62246919e-01, 4.05881322e-01],
       [4.17090736e-01, 6.95591028e-01, 4.24847238e-01, ...,
        4.37268841e-01, 4.21617509e-01, 5.47173771e-02],
       ...,
       [4.21180848e-01, 2.35263416e-01, 9.80352358e-01, ...,
        6.12607432e-01, 3.12077819e-01, 5.26514614e-01],
       [5.11328933e-01, 6.54087787e-01, 7.94117260e-01, ...,
        9.53289789e-01, 5.06908205e-01, 1.06125824e-02],
       [6.48360982e-01, 3.24140378e-04, 7.33029858e-01, ...,
        3.60737582e-01, 3.33155146e-02, 9.24292419e-02]])

In [62]:
# Ejercicio 9
#On the other hand, as of Python 3.5, NumPy supports infix matrix multiplication using the @ operator, 
#so you can achieve the same convenience of matrix multiplication with ndarrays in Python >= 3.5.
#https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u
x@y

array([[19.63024901, 23.68338027, 22.37645147, ..., 22.80913368,
        22.71227398, 23.4805656 ],
       [22.99573912, 27.23556839, 24.34021071, ..., 25.57954755,
        26.11760602, 26.41795842],
       [21.99297998, 27.0840918 , 25.29975326, ..., 24.89278093,
        27.25580459, 25.51898003],
       ...,
       [23.17615805, 27.6636678 , 25.02197825, ..., 25.41408353,
        25.23172214, 26.22435838],
       [21.78750946, 25.68854084, 24.504751  , ..., 21.59803463,
        25.63567495, 24.86482131],
       [20.27361629, 26.19140193, 22.12505359, ..., 22.26103826,
        22.64745267, 24.94344762]])

In [66]:
# Ejercicio 10
np.linalg.inv(x) # inversa
np.linalg.eig(x) # Eigen values matrix and eigen normalized vector matrices

(array([49.73773996+0.j        , -3.11690013+0.j        ,
         1.47821863+2.30748478j,  1.47821863-2.30748478j,
         2.69837853+0.j        ,  2.53643417+0.71493289j,
         2.53643417-0.71493289j,  2.21739424+1.39171248j,
         2.21739424-1.39171248j,  1.77654152+1.95675612j,
         1.77654152-1.95675612j, -0.62742303+2.75030594j,
        -0.62742303-2.75030594j,  0.79579499+2.54959601j,
         0.79579499-2.54959601j,  0.28137288+2.69246528j,
         0.28137288-2.69246528j, -1.00457223+2.55459612j,
        -1.00457223-2.55459612j, -2.78766749+0.j        ,
        -2.62839413+0.79626687j, -2.62839413-0.79626687j,
        -2.23287816+1.54489692j, -2.23287816-1.54489692j,
        -2.195922  +1.34544071j, -2.195922  -1.34544071j,
         0.3721649 +2.43588177j,  0.3721649 -2.43588177j,
        -1.71985907+1.80241215j, -1.71985907-1.80241215j,
         1.32902705+1.89735966j,  1.32902705-1.89735966j,
         2.30022473+0.j        ,  1.95808238+0.80102236j,
         1.958